version: '3.3'

services:

 freeradius:
  image: freeradius/freeradius-server:3.0.21
  ports:
    - target: 1812
      published: 1812
#      protocol: udp
    - target: 1813
      published: 1813
#      protocol: udp
  volumes:

# Mike Note: put the individual files and reference them in here:
  - "./freeradius/config/freeradius:/etc/freeradius"
  - "./freeradius/logs:/var/log/freeradius"

  restart: always
