version: '3.2'

services:

 freeradius:
  image: freeradius/freeradius-server:3.0.21
  ports:
    - "192.168.200.1:1812:1812/udp"
    - "192.168.200.1:1813:1813/udp"
  volumes:
  - "./config/authorize:/etc/freeradius/3.0/mods-config/files/authorize"
  - "./config/authorized_macs:/etc/freeradius/3.0/mods-config/files/authorized_macs"
  - "./config/clients.conf:/etc/freeradius/3.0/clients.conf"
  - "./config/default:/etc/freeradius/3.0/sites-available/default"
  - "./config/eap:/etc/freeradius/3.0/mods-available/eap"
  - "./config/files:/etc/freeradius/3.0/mods-available/files"

  restart: always
