version: '3.2'

services:

 freeradius:
  image: nvidia/radius
  build:
      context: ./
      dockerfile: Dockerfile
  container_name: freeradius-poc
  ports:
    - "1812:1812/udp"
    - "1813:1813/udp"
