- name: Verify Minimum Software Version - Ubuntu 18.04
  assert:
    that: "{{ansible_lsb.release is version_compare('18.04', '>=') }}"
    msg: >
      "Ubuntu must be version 18.04.
      Version {{ansible_lsb.release}} detected"

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes

- name: Install Docker and Docker Compose
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker.io
    - docker-compose

- name: Flush Handlers, best practice
  meta: flush_handlers
